### ISSUE TITLE
Please make this package available through package control

### ISSUE THREAD

**Issue by leon** [guillaumebort/play2-sublimetext2#2]
http://wbond.net/sublime_packages/package_control

That would be awesome!

**Comment by alternegro** [comment]
I second that. If you are too busy, I could do it with your permission.
Cheers

**Comment by Baztoune** [comment]
I just did a [pull request](https://github.com/wbond/package_control_channel/pull/506) on the package control channel to make this package available.

**Comment by leon** [comment]
It's available now :)
